name: Update VLESS Subscription

on:
  schedule:
    - cron: "0 */2 * * *"  # 每 2 小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 或你需要的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python extract_vless_links.py

      - name: Commit changes
        run: |
          git config --global user.name "wstszx"
          git config --global user.email "mywstszx@gmail.com"
          git add subscription.txt
          git commit -m "Update subscription.txt" || echo "No changes to commit"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
